[package]
name = "starbreaker-export"
version = "0.1.0"
edition = "2024"

[dependencies]
starbreaker-parsers = { path = "../starbreaker-parsers" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
image = "0.25"
texpresso = "2.0"
half = "2.4"
bytemuck = "1.14"
